# SPDX-FileCopyrightText: Copyright 2024 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause
arb-dir: lib/shared_preferences/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
