# SPDX-FileCopyrightText: Copyright 2023 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause

name: path_provider_aurora
description: The Aurora OS implementation of path_provider.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  plugin_platform_interface: ^2.0.2
  path_provider_platform_interface: ^2.1.0

  ## https://gitlab.com/omprussia/flutter/flutter-plugins/-/tree/master/packages/xdga_directories
  xdga_directories:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: master
      path: packages/xdga_directories

  ## https://pub.dev/packages/package_info_plus
  package_info_plus: 4.1.0
  ## https://gitlab.com/omprussia/flutter/flutter-plugins/-/tree/master/packages/package_info_plus/package_info_plus_aurora
  package_info_plus_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: master
      path: packages/package_info_plus/package_info_plus_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: path_provider
    platforms:
      aurora:
        dartPluginClass: PathProviderAurora
