# Copyright (c) 2023. Open Mobile Platform LLC.
# License: Proprietary.

name: path_provider_aurora
description: The Aurora OS implementation of path_provider.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  plugin_platform_interface: ^2.0.2
  path_provider_platform_interface: ^2.0.6
  xdga_directories:
    git:
      url: git@os-git.omprussia.ru:non-oss/flutter/flutter-plugins.git
      ref: dev
      path: packages/xdga_directories
  package_info_plus: 4.0.0
  package_info_plus_aurora:
    git:
      url: git@os-git.omprussia.ru:non-oss/flutter/flutter-plugins.git
      ref: dev
      path: packages/package_info_plus/package_info_plus_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: path_provider
    platforms:
      aurora:
        dartPluginClass: PathProviderAurora
