# SPDX-FileCopyrightText: 2023 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause
name: sensors_plus_aurora
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  sensors_plus_platform_interface: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        pluginClass: SensorsPlusAuroraPlugin
        dartPluginClass: SensorsPlusAurora
