# Copyright (C) 2023 Open Mobile Platform LLC.

name: battery_plus_aurora
description: The Aurora OS implementation of battery_plus.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dbus: ^0.7.8
  async: ^2.9.0
  plugin_platform_interface: ^2.0.2
  battery_plus_platform_interface: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        dartPluginClass: BatteryPlusAurora
