# SPDX-FileCopyrightText: Copyright 2024 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause
name: flutter_secure_storage_aurora_example
description: "The Aurora OS example of flutter_secure_storage_aurora."
publish_to: 'none'

version: 3.0.3+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: any
  internal:
    path: ../../../../internal
  flutter_secure_storage: ^9.0.0
  flutter_secure_storage_aurora:
    path: ../

flutter:
  uses-material-design: true
