# Copyright (c) 2023. Open Mobile Platform LLC.
# License: Proprietary.

name: flutter_secure_storage_aurora
description: The Aurora OS implementation of flutter_secure_storage.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.1
  plugin_platform_interface: ^2.0.2
  flutter_secure_storage_platform_interface: ^1.0.1
  path: ^1.8.2
  path_provider: ^2.0.14
  path_provider_aurora:
    git:
      url: git@os-git.omprussia.ru:non-oss/flutter/flutter-plugins.git
      ref: dev
      path: packages/path_provider/path_provider_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        dartPluginClass: FlutterSecureStorageAurora
