# Copyright (c) 2023. Open Mobile Platform LLC.
# License: Proprietary.

name: battery_plus_aurora_example
description: Demonstrates how to use the battery_plus_aurora plugin.

publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  battery_plus: ^4.0.1
  battery_plus_aurora:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
