# SPDX-FileCopyrightText: Copyright 2023 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause

name: xdga_directories
description: Plugin for Aurora OS like xdg_directories
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^7.2.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        ffiPlugin: true
