# Copyright (c) 2023. Open Mobile Platform LLC.
# License: Proprietary.

name: shared_preferences_aurora
description: The Aurora OS implementation of shared_preferences.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.1.1
  shared_preferences_platform_interface: ^2.2.0
  path: ^1.8.2
  path_provider: ^2.0.14
  path_provider_aurora:
    git:
      url: git@os-git.omprussia.ru:non-oss/flutter/flutter-plugins.git
      ref: dev
      path: packages/path_provider/path_provider_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        dartPluginClass: SharedPreferencesAurora
