# Copyright (C) 2023 Open Mobile Platform LLC.

name: wakelock_aurora
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dbus: ^0.7.8
  plugin_platform_interface: ^2.0.2
  wakelock_platform_interface: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        dartPluginClass: WakelockAurora
