# Copyright (c) 2023. Open Mobile Platform LLC.
# License: Proprietary.

name: flutter_local_notifications_aurora_example
description: Demonstrates how to use the flutter_local_notifications_aurora plugin.

publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0+2
  flutter_local_notifications_aurora:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
