# SPDX-FileCopyrightText: Copyright 2023 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause
name: internal
description: A package to simplify and organize plugins example.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_keyboard_visibility: ^5.4.1
  flutter_keyboard_visibility_aurora:
      path: ../packages/flutter_keyboard_visibility/flutter_keyboard_visibility_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
