# Copyright (c) 2023. Open Mobile Platform LLC.
# License: Proprietary.

name: sqflite_aurora
description: The Aurora OS implementation of sqflite.
version: 2.2.6+aurora1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.6

flutter:
  plugin:
    platforms:
      aurora:
        dartPluginClass: SqfliteAurora
        pluginClass: SqfliteAuroraPlugin
