name: sqflite_example
description: Demonstrates how to use the sqflite_aurora plugin.

publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.6
  sqflite_common: ^2.4.4
  sqflite_aurora:
    path: ../

  cupertino_icons: ^1.0.2
  path: ^1.8.2
  synchronized: ^3.1.0
  collection: ^1.16.0
  matcher: ^0.12.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/example.db
    - assets/issue_64.db
