# SPDX-FileCopyrightText: Copyright 2023 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause

name: device_info_plus_aurora
description: The Aurora OS implementation of flutter_local_notifications.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dbus: ^0.7.8
  device_info_plus: ^9.0.3
  plugin_platform_interface: ^2.0.2
  device_info_plus_platform_interface: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        dartPluginClass: DeviceInfoPlusAurora
